#:kivy 2.1.0

#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include screen_splash.kv
#:include screen_setting.kv
#:include screen_data.kv
#:include screen_graph.kv

<RootScreen>:
    id: screen_manager
    transition: NoTransition()

    ScreenSplash:
        id: screen_splash
        name: 'screen_splash'
        screen_manager: screen_manager

    ScreenSetting:
        id: screen_setting
        name: 'screen_setting'
        screen_manager: screen_manager

    ScreenData:
        id: screen_data
        name: 'screen_data'
        screen_manager: screen_manager
         
    ScreenGraph:
        id: screen_graph
        name: 'screen_graph'
        screen_manager: screen_manager
                  
